- name: create backend dir
  file:
    path: ~/backend-application
    state: directory

- name: extract backend files
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-application

- name: "install pm2"
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: install node dep
  shell: |
    cd ~/backend-application
    npm i

- name: Exec node
  # shell: |
  #   cd ~/backend-application/dist
  #   pm2 stop default
  #   pm2 start main.js

  command: |
    cd ~/backend-application/dist
    pm2 stop default
    pm2 start main.js
  args:
    chdir: ~/backend-application/dist
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"

  register: exec_node

- name: print msg
  debug:
    msg: "{{ exec_node.stdout_lines}}"

- name: configure pm2 to start AAS
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
